---
- name: enable epl release
  yum: 
    name: epel-release
    state: present

- name: ensure node and npm present
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: epel
  with_items:
    - nodejs
    - npm

- name: ensure default npm packages present
  npm:
    name: "{{ item }}"
    global: yes
  with_items: npm_packages

- name: Set explicit versions of node and npm
  command:
    name: "/usr/lib/node_modules/npm cache clean -f"
  command: 
    name: "/usr/lib/node_modules/npm install -g n"
  command:
    name: "/usr/bin/n {{ __node_version }}"
  command:
    name: "/bin/ln -sf /usr/local/n/versions/node/{{ __node_version }}/bin/node /usr/local/bin/node"
  command:
    name: "/usr/lib/node_modules/npm install -g npm@{{ __npm_version }}"
  command:
    name: "/bin/ln -sf /usr/local/n/versions/node/{{ __node_version }}/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm"