---
- name: enable epl release
  yum: 
    name: epel-release
    state: present

- name: ensure node and npm present
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: epel
  with_items:
    - nodejs
    - npm

- name: ensure default npm packages present
  npm:
    name: "{{ item }}"
    global: yes
  with_items: npm_packages

- name: Clear and clean npm cache
  shell: "npm cache clean -f"

- name: Install n to manage versions of node
  shell: "npm install -g n"

- name: Use n to install newer node
  shell: "n {{ __node_version }}"

- name: Use npm to install new version of npm
  shell: "npm install -g npm@{{ __npm_version }}"

- name: Create alternatives link for npm
  file:
    dest: /usr/local/bin/npm
    src: /usr/lib/node_modules/npm/bin/npm-cli.js
    state: link
    force: true

- name: Create alternatives link for node
  file:
    dest: /usr/local/bin/node
    src: /usr/local/n/versions/node/{{ __node_version }}/bin/node
    state: link
    force: true


